;
; File generated by cc65 v 2.13.2
;
	.fopt		compiler,"cc65 v 2.13.2"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank, tmp1, ptr1, ptr2
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_clrscr
	.import		_cprintf
	.export		_main

.segment	"RODATA"

L0001:
	.byte	$53,$74,$61,$72,$74,$69,$6E,$67,$20,$43,$6F,$6E,$74,$72,$6F,$6C
	.byte	$6C,$65,$72,$20,$54,$65,$73,$74,$0A,$0D,$00,$4A,$6F,$79,$70,$61
	.byte	$64,$20,$31,$20,$46,$6F,$75,$6E,$64,$0A,$0D,$00,$41,$00,$42,$00
	.byte	$53,$65,$6C,$65,$63,$74,$00,$53,$74,$61,$72,$74,$00,$55,$70,$00
	.byte	$44,$6F,$77,$6E,$00,$4C,$65,$66,$74,$00,$52,$69,$67,$68,$74,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldy     #$11
	jsr     subysp
	ldx     #$00
	lda     #$00
	ldy     #$10
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$0F
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$0E
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$0D
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$0C
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$0B
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$0A
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$09
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$08
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$07
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$06
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$05
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$04
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$03
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$02
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$01
	sta     (sp),y
	jsr     _clrscr
	lda     #<(L0001)
	ldx     #>(L0001)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
	ldx     #$00
	lda     #$01
	sta     $4016
	ldx     #$00
	lda     #$00
	sta     $4016
	ldx     #$00
	lda     #$01
	ldy     #$00
	sta     (sp),y
L002A:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$15
	jsr     boolult
	jne     L002D
	jmp     L002B
L002D:	ldx     #$00
	lda     $4016
	ldy     #$10
	sta     (sp),y
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$00
	sta     (sp),y
	pla
	jmp     L002A
L002B:	ldy     #$10
	ldx     #$00
	lda     (sp),y
	cmp     #$41
	jsr     booleq
	jeq     L0034
	lda     #<(L0001+27)
	ldx     #>(L0001+27)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
L0034:	ldx     #$00
	lda     #$00
	ldy     #$10
	sta     (sp),y
	ldx     #$00
	lda     #$01
	sta     $4016
	ldx     #$00
	lda     #$00
	sta     $4016
L003E:	ldx     #$00
	lda     $4016
	ldy     #$10
	sta     (sp),y
	ldy     #$10
	ldx     #$00
	lda     (sp),y
	cmp     #$41
	jsr     booleq
	jeq     L0046
	ldy     #$0F
	ldx     #$00
	lda     (sp),y
	cmp     #$40
	jsr     booleq
	jne     L0044
L0046:	ldx     #$00
	lda     #$00
	jeq     L0048
L0044:	ldx     #$00
	lda     #$01
L0048:	jeq     L0043
	lda     #<(L0001+44)
	ldx     #>(L0001+44)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
L0043:	ldx     #$00
	lda     $4016
	ldy     #$0E
	sta     (sp),y
	ldy     #$0E
	ldx     #$00
	lda     (sp),y
	cmp     #$41
	jsr     booleq
	jeq     L0050
	ldy     #$0D
	ldx     #$00
	lda     (sp),y
	cmp     #$40
	jsr     booleq
	jne     L004E
L0050:	ldx     #$00
	lda     #$00
	jeq     L0052
L004E:	ldx     #$00
	lda     #$01
L0052:	jeq     L004D
	lda     #<(L0001+46)
	ldx     #>(L0001+46)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
L004D:	ldx     #$00
	lda     $4016
	ldy     #$0C
	sta     (sp),y
	ldy     #$0C
	ldx     #$00
	lda     (sp),y
	cmp     #$41
	jsr     booleq
	jeq     L005A
	ldy     #$0B
	ldx     #$00
	lda     (sp),y
	cmp     #$40
	jsr     booleq
	jne     L0058
L005A:	ldx     #$00
	lda     #$00
	jeq     L005C
L0058:	ldx     #$00
	lda     #$01
L005C:	jeq     L0057
	lda     #<(L0001+48)
	ldx     #>(L0001+48)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
L0057:	ldx     #$00
	lda     $4016
	ldy     #$0A
	sta     (sp),y
	ldy     #$0A
	ldx     #$00
	lda     (sp),y
	cmp     #$41
	jsr     booleq
	jeq     L0064
	ldy     #$09
	ldx     #$00
	lda     (sp),y
	cmp     #$40
	jsr     booleq
	jne     L0062
L0064:	ldx     #$00
	lda     #$00
	jeq     L0066
L0062:	ldx     #$00
	lda     #$01
L0066:	jeq     L0061
	lda     #<(L0001+55)
	ldx     #>(L0001+55)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
L0061:	ldx     #$00
	lda     $4016
	ldy     #$08
	sta     (sp),y
	ldy     #$08
	ldx     #$00
	lda     (sp),y
	cmp     #$41
	jsr     booleq
	jeq     L006E
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	cmp     #$40
	jsr     booleq
	jne     L006C
L006E:	ldx     #$00
	lda     #$00
	jeq     L0070
L006C:	ldx     #$00
	lda     #$01
L0070:	jeq     L006B
	lda     #<(L0001+61)
	ldx     #>(L0001+61)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
L006B:	ldx     #$00
	lda     $4016
	ldy     #$06
	sta     (sp),y
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	cmp     #$41
	jsr     booleq
	jeq     L0078
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	cmp     #$40
	jsr     booleq
	jne     L0076
L0078:	ldx     #$00
	lda     #$00
	jeq     L007A
L0076:	ldx     #$00
	lda     #$01
L007A:	jeq     L0075
	lda     #<(L0001+64)
	ldx     #>(L0001+64)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
L0075:	ldx     #$00
	lda     $4016
	ldy     #$04
	sta     (sp),y
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	cmp     #$41
	jsr     booleq
	jeq     L0082
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	cmp     #$40
	jsr     booleq
	jne     L0080
L0082:	ldx     #$00
	lda     #$00
	jeq     L0084
L0080:	ldx     #$00
	lda     #$01
L0084:	jeq     L007F
	lda     #<(L0001+69)
	ldx     #>(L0001+69)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
L007F:	ldx     #$00
	lda     $4016
	ldy     #$02
	sta     (sp),y
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	cmp     #$41
	jsr     booleq
	jeq     L008C
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	cmp     #$40
	jsr     booleq
	jne     L008A
L008C:	ldx     #$00
	lda     #$00
	jeq     L008E
L008A:	ldx     #$00
	lda     #$01
L008E:	jeq     L0089
	lda     #<(L0001+74)
	ldx     #>(L0001+74)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
L0089:	ldy     #$10
	ldx     #$00
	lda     (sp),y
	ldy     #$0F
	sta     (sp),y
	ldy     #$0E
	ldx     #$00
	lda     (sp),y
	ldy     #$0D
	sta     (sp),y
	ldy     #$0C
	ldx     #$00
	lda     (sp),y
	ldy     #$0B
	sta     (sp),y
	ldy     #$0A
	ldx     #$00
	lda     (sp),y
	ldy     #$09
	sta     (sp),y
	ldy     #$08
	ldx     #$00
	lda     (sp),y
	ldy     #$07
	sta     (sp),y
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	ldy     #$05
	sta     (sp),y
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	ldy     #$03
	sta     (sp),y
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	ldx     #$00
	lda     #$01
	sta     $4016
	ldx     #$00
	lda     #$00
	sta     $4016
	jmp     L003E
	ldy     #$11
	jsr     addysp
	rts

.endproc

