;
; File generated by cc65 v 2.13.2

	.fopt		compiler,"cc65 v 2.13.2"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.macpack	longbranch

.segment	"CHARS"

.incbin "..\gfx\bkg.bin"
.incbin "..\gfx\spr.bin"